<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Aquí {cats, plural, =0{no hay gatos} =1{hay un gato} other{hay # gatos}}!' => 'There {cats, plural, =0{are not cats} =1{is a cat} other{are # cats}}!',
    'Hola, {username}!' => 'Hi, {username}!',
    'Hoy: {0, date, dd-M-yyyy}' => 'Today: {0, date, yyyy-M-dd}',
    'Precio: {0, number, integer}' => 'Price: {0, number, integer}',
    'Precio: {0}' => 'Price: {0}',
    'Precio: {0}, Conteo: {1}, Subtotal: {2}' => 'Price: {0}, Count: {1}, Subtotal: {2}',
    'Tu edad es {age}' => 'Your age is {age}',
];
